name: keepalive
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cronjob:
    name: Cronjob
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
