name: 自动任务

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "30 21 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天早上5点半自动执行

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 下载node依赖
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install axios
      - run: npm install lodash
      - name: 执行脚本
        env:
          COOKIE: ${{ secrets.COOKIE }}
          FEISHU_WEB_HOOK: ${{ secrets.FEISHU_WEB_HOOK }}
        run: node src/index.js
