name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  main:
    runs-on: ubuntu-latest

    steps:   
    - uses: actions/checkout@v2
    - name: install
      run: |
        sudo npm install axios
    - name: main
      run: |
        node main.js --cookie ${secrets.COOKIE}
