name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  main:
    runs-on: ubuntu-latest

    steps:    
    - name: main
      run: |
        node main.js
