name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  main:
    runs-on: ubuntu-latest

    steps:   
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install axios
    - name: main
      env:
        COOKIE: ${{ secrets.COOKIE }}
      run: |
        COOKIE="$env:SUPER_SECRET" node main.js
